INSERT INTO productos (CODIGOARTICULO, SECCION, NOMBREARTICULO, PRECIO, FECHA, IMPORTADO, PAISDEORIGEN)
VALUES 
('AR42', 'DEPORTES', 'CAMISETA CORRER',   NULL,  NULL, 			NULL, NULL),
('AR44', 'DEPORTES', 'RAQUETA BADMINTON', NULL,  NULL, 			NULL, NULL),
('AR88', 'DEPORTES', 'BALÓN BALONMANO',   40.00, NULL, 			1, 'USA'),
('AR89', 'DEPORTES', 'BALÓN BALONMANO',   40.00, '2015-08-20', 1, 'USA');