-- Mostrar los clientes de Madrid que han hecho pedidos
-- Inner join estándar
SELECT c.EMPRESA, c.DIRECCION, c.POBLACION, c.TELEFONO, c.RESPONSABLE, p.*
FROM clientes c
INNER JOIN pedidos p
ON c.CODIGOCLIENTE = p.CODIGOCLIENTE
WHERE c.POBLACION LIKE 'MADRID'
ORDER BY c.CODIGOCLIENTE ASC, p.NUMERODEPEDIDO ASC;

-- Inner join default
SELECT c.EMPRESA, c.DIRECCION, c.POBLACION, c.TELEFONO, c.RESPONSABLE, p.*
FROM clientes c
JOIN pedidos p
ON c.CODIGOCLIENTE = p.CODIGOCLIENTE
WHERE c.POBLACION LIKE 'MADRID'
ORDER BY c.CODIGOCLIENTE ASC, p.NUMERODEPEDIDO ASC;

-- Inner join implícito
SELECT c.EMPRESA, c.DIRECCION, c.POBLACION, c.TELEFONO, c.RESPONSABLE, p.*
FROM clientes c, pedidos p
WHERE  
	c.CODIGOCLIENTE = p.CODIGOCLIENTE
AND 
	c.POBLACION LIKE 'MADRID'
ORDER BY c.CODIGOCLIENTE ASC, p.NUMERODEPEDIDO ASC