-- Left join: Mostrar los clientes de Madrid que no han hecho pedidos
SELECT c.CODIGOCLIENTE, c.POBLACION, c.DIRECCION, p.NUMERODEPEDIDO, p.CODIGOCLIENTE, p.FORMADEPAGO
FROM clientes c
LEFT JOIN pedidos p
ON c.CODIGOCLIENTE = p.CODIGOCLIENTE
WHERE c.POBLACION LIKE 'MADRID' AND p.CODIGOCLIENTE IS NULL;