-- Eliminar los clientes que no han hecho pedidos
BEGIN;
	DELETE c.*
	FROM clientes c
	LEFT JOIN pedidos p
	ON c.CODIGOCLIENTE = p.CODIGOCLIENTE
	WHERE p.CODIGOCLIENTE IS NULL;

	SELECT c.CODIGOCLIENTE, c.EMPRESA, c.POBLACION, p.NUMERODEPEDIDO, p.FORMADEPAGO, p.FECHADEPEDIDO 
	FROM clientes c
	LEFT JOIN pedidos p
	ON c.CODIGOCLIENTE = p.CODIGOCLIENTE
	WHERE p.CODIGOCLIENTE IS NULL;
ROLLBACK;