-- Clientes y sus pedidos
SELECT c.CODIGOCLIENTE, c.EMPRESA, c.POBLACION, p.NUMERODEPEDIDO, p.FORMADEPAGO, p.FECHADEPEDIDO 
FROM clientes c
INNER JOIN pedidos p
ON c.CODIGOCLIENTE = p.CODIGOCLIENTE
ORDER BY p.CODIGOCLIENTE ASC, p.NUMERODEPEDIDO ASC;