-- Clientes que no han hecho pedidos
SELECT c.CODIGOCLIENTE, c.EMPRESA, c.POBLACION, p.NUMERODEPEDIDO, p.FORMADEPAGO, p.FECHADEPEDIDO 
FROM clientes c
LEFT JOIN pedidos p
ON c.CODIGOCLIENTE = p.CODIGOCLIENTE
WHERE p.CODIGOCLIENTE IS NULL;