FROM node:22.22.0-slim

WORKDIR /app

COPY package*.json ./

RUN npm install

# En modo dev el COPY es casi de respaldo, el volumen hará el trabajo duro
COPY . .

EXPOSE 3000

# Separación estricta de argumentos
CMD ["node", "--watch", "index.js"]