-- Calcular la diferencia entre dos fechad
SELECT NOMBREARTICULO, SECCION, PRECIO, FECHA, DATE_FORMAT(NOW(), '%Y-%m-%d') AS DIA_ACTUAL, 
DATEDIFF(NOW(), FECHA) AS DIF_DIAS, TIMESTAMPDIFF(MONTH, FECHA , NOW()) AS DIF_MESES, TIMESTAMPDIFF(YEAR, FECHA, NOW()) AS DIF_ANIOS
FROM productos
WHERE SECCION LIKE 'DEPORTES';