-- Testing para comparar ambas soluciones y ver diferencias en resultados
SELECT a.* FROM (SELECT p.NOMBREARTICULO, p.PRECIO
FROM productos p
WHERE p.CODIGOARTICULO IN (SELECT pp.CODIGOARTICULO FROM productos_pedidos pp GROUP BY pp.CODIGOARTICULO HAVING SUM(pp.UNIDADES) > 20)
ORDER BY p.PRECIO DESC) a
WHERE a.NOMBREARTICULO NOT IN (SELECT b.NOMBREARTICULO FROM (SELECT p.NOMBREARTICULO, p.PRECIO 
FROM productos p
WHERE p.CODIGOARTICULO IN (SELECT pp.CODIGOARTICULO FROM productos_pedidos pp WHERE pp.UNIDADES > 20)
ORDER BY p.PRECIO DESC) b);

